"use strict";

module.exports = {
  rules: {
    "getter-return": 2,
    "no-await-in-loop": 1,
    "no-console": 1,
    "no-inner-declarations": 2,
    "no-setter-return": 2,
    "consistent-return": 2,
    "default-case": 2,
    "guard-for-in": 2,
    "max-classes-per-file": 2,
    "no-alert": 1,
    "no-else-return": 2,
    "no-empty-function": 1,
    "no-extra-label": 2,
    "no-param-reassign": [2, { props: true, ignorePropertyModificationsFor: ["draft"] }],
    "no-return-await": 1,
    "no-script-url": 2,
    "no-unused-labels": 2,
    "no-shadow": 2,
    "no-lonely-if": 1,
    "no-bitwise": 2,
    "no-continue": 2,
    "no-multi-assign": 2,
    "no-nested-ternary": 1,
    "operator-assignment": [2, "always"],
    "prefer-object-spread": 2,
    "prefer-destructuring": 1,
    "prefer-rest-params": 2,
    "prefer-template": 2,
    "import/no-extraneous-dependencies": [
      2,
      {
        devDependencies: ["**/*.test.ts","**/*.test.tsx","**/*.stories.tsx"],
        optionalDependencies: false,
      },
    ],
    "@typescript-eslint/no-unused-vars": [2, { argsIgnorePattern: "^__", ignoreRestSiblings: true }],
    "@typescript-eslint/no-use-before-define": 2,
    "@typescript-eslint/no-useless-constructor": 2,
    "import/no-cycle": 1,
    "import/extensions": 0,
    "no-array-constructor": 0,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    "no-useless-constructor": 0,
    "react-hooks/exhaustive-deps": 2,
    "react/prop-types": 0,
    "jsx-a11y/anchor-is-valid": [
      2,
      {
        components: ["Link"],
        specialLink: ["to", "onClick"],
      },
    ],
  },
};
